#ifndef MYSQLDEMOLIB_GLOBAL_H
#define MYSQLDEMOLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYSQLDEMOLIB_LIBRARY)
#  define MYSQLDEMOLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYSQLDEMOLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYSQLDEMOLIB_GLOBAL_H
